project_id = "jelbyajfzvpeegwjpwpt"

[functions.send-whatsapp]
verify_jwt = false

[functions.queue-worker]
verify_jwt = false

[functions.webhook-whatsapp]
verify_jwt = false

[functions.medications-search]
verify_jwt = false
