
-- New fields for enhanced Psychology anamnesis
ALTER TABLE public.patient_anamnese_psicologia
  ADD COLUMN IF NOT EXISTS quem_sugeriu_terapia text,
  ADD COLUMN IF NOT EXISTS quando_comecou text,
  ADD COLUMN IF NOT EXISTS situacoes_associadas text,
  ADD COLUMN IF NOT EXISTS frequencia_sintomas text,
  ADD COLUMN IF NOT EXISTS intensidade_subjetiva text,
  ADD COLUMN IF NOT EXISTS impacto_vida text,
  ADD COLUMN IF NOT EXISTS estrategias_tentadas text,
  ADD COLUMN IF NOT EXISTS infancia text,
  ADD COLUMN IF NOT EXISTS adolescencia text,
  ADD COLUMN IF NOT EXISTS eventos_marcantes text,
  ADD COLUMN IF NOT EXISTS experiencias_traumaticas text,
  ADD COLUMN IF NOT EXISTS relacionamento_pais_cuidadores text,
  ADD COLUMN IF NOT EXISTS contexto_rede_apoio text,
  ADD COLUMN IF NOT EXISTS contexto_atividade_fisica text,
  ADD COLUMN IF NOT EXISTS humor_predominante text,
  ADD COLUMN IF NOT EXISTS ansiedade text,
  ADD COLUMN IF NOT EXISTS irritabilidade text,
  ADD COLUMN IF NOT EXISTS concentracao text,
  ADD COLUMN IF NOT EXISTS autoestima text,
  ADD COLUMN IF NOT EXISTS pensamentos_recorrentes text,
  ADD COLUMN IF NOT EXISTS ideacao_suicida boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS ideacao_suicida_obs text,
  ADD COLUMN IF NOT EXISTS comportamentos_risco text,
  ADD COLUMN IF NOT EXISTS observacao_postura text,
  ADD COLUMN IF NOT EXISTS observacao_afeto text,
  ADD COLUMN IF NOT EXISTS observacao_linguagem text,
  ADD COLUMN IF NOT EXISTS observacao_insight text,
  ADD COLUMN IF NOT EXISTS observacao_coerencia_discurso text,
  ADD COLUMN IF NOT EXISTS observacoes_objetivos text,
  ADD COLUMN IF NOT EXISTS abordagem_terapeutica text,
  ADD COLUMN IF NOT EXISTS frequencia_sessoes text,
  ADD COLUMN IF NOT EXISTS encaminhamentos text,
  ADD COLUMN IF NOT EXISTS intervencoes_previstas text;
